name: Build-Deploy
on:
  push:
    branches-ignore:
      - main
  pull_request:
    types: [closed]

jobs:
  build-and-deploy-artifact:
    name: Build and deploy to github package
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v4

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # ratchet:actions/setup-java@v5.2.0
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Resolve/Update Dependencies
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --settings .m2/maven-settings.xml package dependency:resolve-plugins dependency:go-offline

      - name: Build (and run tests)
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.cache.outputs.cache-hit != 'true'
        run: mvn --settings .m2/maven-settings.xml clean install

      - name: Save test results
        run: |
          mkdir -p ~/test-results/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;

      - name: Setting version
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.base_ref == 'main' && github.event.pull_request.merged == true
        run: |
          export GIT_COMMIT_HASH=$(git log -n 1 --pretty=format:'%h')
          export GIT_COMMIT_DATE=$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')
          export VERSION=3.${GIT_COMMIT_DATE}_${GIT_COMMIT_HASH}
          echo "Setting version $VERSION"
          mvn --settings .m2/maven-settings.xml versions:set -DnewVersion="$VERSION"
          mvn --settings .m2/maven-settings.xml versions:commit

      - name: Deploy to Github Package
        if: github.base_ref == 'main' && github.event.pull_request.merged == true
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --settings .m2/maven-settings.xml source:jar-no-fork deploy -DskipTests=true -Dmaven.wagon.http.pool=false

      - name: Post build failures to Slack
        if: github.base_ref == 'main' && failure()
        run: |
          curl -X POST --data "{\"text\": \"Build av $GITHUB_REPOSITORY feilet - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
